# PATH
# eval "$(/usr/libexec/path_helper -c)"

# if [ -x /opt/homebrew/bin/brew ]
#     eval "$(/opt/homebrew/bin/brew shellenv)"
# end

# Generated by `/opt/homebrew/bin/brew shellenv`
set --global --export HOMEBREW_PREFIX "/opt/homebrew";
set --global --export HOMEBREW_CELLAR "/opt/homebrew/Cellar";
set --global --export HOMEBREW_REPOSITORY "/opt/homebrew";
fish_add_path --global --move --path "/opt/homebrew/bin" "/opt/homebrew/sbin";
if test -n "$MANPATH[1]"; set --global --export MANPATH '' $MANPATH; end;
if not contains "/opt/homebrew/share/info" $INFOPATH; set --global --export INFOPATH "/opt/homebrew/share/info" $INFOPATH; end;

set -gx PATH \
    $HOME/bin \
    $HOME/.oh-my-configs/bin \
    $HOME/.local/bin \
    $HOME/.cargo/bin \
    $HOME/.yarn/bin \
    $HOME/.cache/lm-studio/bin \
    $PATH

# Path Alias
abbr --add ~code ~/Code
